version: '3.9'

services:
  usuarios:
    build:
      context: .
      dockerfile: Usuarios_Dockerfile
    container_name: usuarios
    ports:
      - "8081:8081"
    environment:
      - FLASK_ENV=production
    networks:
      custom_network:
        ipv4_address: 172.20.0.2

  mascotas:
    build:
      context: .
      dockerfile: Mascotas_Dockerfile
    container_name: mascotas
    ports:
      - "8082:8082"
    environment:
      - FLASK_ENV=production
    networks:
      custom_network:
        ipv4_address: 172.20.0.3
  
  visitas:
    build:
      context: .
      dockerfile: Visitas_Dockerfile
    container_name: visitas
    ports:
      - "8083:8083"
    environment:
      - FLASK_ENV=production
    networks:
      custom_network:
        ipv4_address: 172.20.0.4

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
